// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Controllers.AuthController.Register(Coupons.PepsiKSA.Api.Core.ModelDto.UserRegisterDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Controllers.CouponsController.BurnCoupon(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.ToString()' could vary based on the current user's locale settings. Replace this call in 'EcouponsService.EBurn(ECouponBurnRequest)' with a call to 'int.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.E_Coupons.EcouponsService.EBurn(Coupons.PepsiKSA.Api.Core.ModelDto.ECouponBurnRequest)~System.Threading.Tasks.Task{Coupons.PepsiKSA.Api.Core.ModelDto.ECouponBurnResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SCS0005:Weak random generator", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.E_Coupons.EcouponsService.EBurn(Coupons.PepsiKSA.Api.Core.ModelDto.ECouponBurnRequest)~System.Threading.Tasks.Task{Coupons.PepsiKSA.Api.Core.ModelDto.ECouponBurnResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.ToString()' could vary based on the current user's locale settings. Replace this call in 'EcouponsService.EcouponsRegister(UserRegisterDto)' with a call to 'int.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.E_Coupons.EcouponsService.EcouponsRegister(Coupons.PepsiKSA.Api.Core.ModelDto.UserRegisterDto)~System.Threading.Tasks.Task{Coupons.PepsiKSA.Api.Core.ModelDto.EcouponsRegisterResponseDto}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SCS0005:Weak random generator", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.E_Coupons.EcouponsService.EcouponsRegister(Coupons.PepsiKSA.Api.Core.ModelDto.UserRegisterDto)~System.Threading.Tasks.Task{Coupons.PepsiKSA.Api.Core.ModelDto.EcouponsRegisterResponseDto}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new StringContent(JsonConvert.SerializeObject(content), Encoding.UTF8, \"application/json\")' before all references to it are out of scope", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.HttpFactory.HttpFactory.ClientPostAsync``2(System.String,``0)~System.Threading.Tasks.Task{``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new StringContent(JsonConvert.SerializeObject(content), Encoding.UTF8, \"application/json\")' before all references to it are out of scope", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.HttpFactory.HttpFactory.ClientPostAsync``2(System.String,``0,System.Collections.Generic.Dictionary{System.String,System.String})~System.Threading.Tasks.Task{``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new SmtpClient' before all references to it are out of scope", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.MailService.MailService.Send(Coupons.PepsiKSA.Api.Core.ModelDto.EmailProperties)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'MailService.Send(EmailProperties)' with a call to 'int.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Integrations.MailService.MailService.Send(Coupons.PepsiKSA.Api.Core.ModelDto.EmailProperties)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1304:The behavior of 'string.ToLower()' could vary based on the current user's locale settings. Replace this call in 'AuthRepository.EmailExist(string)' with a call to 'string.ToLower(CultureInfo)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.AuthRepository.EmailExist(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SCS0005:Weak random generator", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.AuthRepository.GenerateOTP(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.ToString()' could vary based on the current user's locale settings. Replace this call in 'AuthRepository.GenerateToken(User)' with a call to 'int.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.AuthRepository.GenerateToken(Coupons.PepsiKSA.Api.Presistence.Models.User)~Coupons.PepsiKSA.Api.Core.ModelDto.AuthDto")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1304:The behavior of 'string.ToLower()' could vary based on the current user's locale settings. Replace this call in 'TransactionRepository.ExportRewards(string)' with a call to 'string.ToLower(CultureInfo)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.TransactionRepository.ExportRewards(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'DateTime.ToString(string)' could vary based on the current user's locale settings. Replace this call in 'TransactionRepository.ExportRewards(string)' with a call to 'DateTime.ToString(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.TransactionRepository.ExportRewards(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'DateTime.ToString(string)' could vary based on the current user's locale settings. Replace this call in 'UserRepository.GetUsersReport()' with a call to 'DateTime.ToString(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Coupons.PepsiKSA.Api.Presistence.Repository.UserRepository.GetUsersReport~System.Threading.Tasks.Task")]